### ISSUE TITLE
wildcard in topic

### ISSUE THREAD

**Issue by Hippoi** [curzon01/mqtt2mysql#2]
Hello

Is it possible to use wildcards in the "topic" parameter?

That is, what would I have to put in order for me to get all messages from a server regardless of topic?

Thansk,
Very good code.

**Comment by curzon01** [comment]
Yes, wildcard is possible, e.g.

`--topic 'myhome/sensors/#'`

to get all topics down to "myhome/sensors"

or

`--topic '#'`

to retrive the complete set of topics from a server.
